export interface CategoryDummy {
    name: string;
    createdAt: string;
    updatedAt: string;
}

export const categories: CategoryDummy[] = [
    { name: "Fantasy", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Dystopian", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Classic", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Romance", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Horror", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Sci-Fi", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Mystery", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Thriller", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Adventure", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Children", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Young Adult", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Historical", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Epic", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Philosophical", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Comedy", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Drama", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Poetry", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Biography", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Autobiography", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Classic Literature", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Gothic", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Crime", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Political", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Epic Fantasy", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Science Fiction", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Paranormal", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Tech", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Self-help", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Motivation", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Philosophy", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Education", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Satire", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Mythology", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Fantasy Adventure", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Science", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Psychology", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Children Classic", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "YA Fiction", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Literary Fiction", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Parable", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Religion", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Classic Horror", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Travel", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Memoir", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Children Fantasy", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Fantasy Comedy", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Modern Novel", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Crime Thriller", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { name: "Contemporary Fiction", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }
];